name:                rwcrypto
version:             0.1.0.0
github:              "githubuser/rwcrypto"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rwcrypto#readme>

dependencies:
- base ^>= 4.20
- ghc ^>= 9.10
- directory ^>= 1.3
- filepath ^>= 1.5
- lens ^>= 5.3
- rewire-user ^>= 0.2
- text ^>= 2.1
- vector
- monad-resumption
- mtl
- ghc-typelits-natnormalise

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wno-name-shadowing
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
    - src
    - src/blake2b
#    - src/sha3
#    - src/sha256
    # - src/salsa20
    # - src/aes
    # - src/pipelining
    # - src/cubehash
#    - external/BinaryArithmetic/src
  exposed-modules:
    - Cubehash.CubeHash8_1_256
    - Cubehash.Simplest
    - Salsa20.ColumnRound
    - Salsa20.DoubleRound
    - Salsa20.Encrypt
    - Salsa20.Expansion
    - Salsa20.HashSalsa20
    - Salsa20.LittleEndian
    - Salsa20.QuarterRound
    - Salsa20.RowRound
    - Salsa20.Testing
    - Salsa20.Test_ColumnRound
    - Salsa20.Test_DoubleRound
    - Salsa20.Test_Encrypt
    - Salsa20.Test_Expansion
    - Salsa20.Test_HashSalsa20
    - Salsa20.Test_LittleEndian
    - Salsa20.Test_QuarterRound
    - Salsa20.Test_RowRound


executables:
  rwcrypto-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rwcrypto

tests:
  rwcrypto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rwcrypto
